#!/bin/bash

# Define colors
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo  "${GREEN}Running Test...${NC}"
npx jest --coverage
if [ $? -ne 0 ]; then
  echo "${RED}Test failed. Coverage below Threshold %.${NC}"
  exit 1
fi
echo  "${GREEN}Test completed with coverage >= Threshold %.${NC}"

echo  "${GREEN}Running ESLint...${NC}"
npx eslint --quiet '**/*.{js,ts}'
if [ $? -ne 0 ]; then
  echo "${RED}ESLint found errors. Please fix the issues and try again.${NC}"
  exit 1
fi

echo  "${GREEN}Running Prettier...${NC}"
npx prettier --check '**/*.{js,ts}'
if [ $? -ne 0 ]; then
  echo "${RED}Prettier check failed. Please format your code and try again.${NC}"
  exit 1
fi

echo  "${GREEN}Pre-commit hook completed successfully.${NC}"
