#!/bin/bash

# Define colors
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo  "${GREEN}Running Test...${NC}"
npx jest
echo  "${GREEN}Test completed.${NC}"

echo  "${GREEN}Running ESLint...${NC}"
npx eslint --fix '**/*.{js,ts}'
echo  "${GREEN}ESLint completed.${NC}"

echo  "${GREEN}Running Prettier...${NC}"
npx prettier --write '**/*.{js,ts}'
echo  "${GREEN}Prettier completed.${NC}"

echo  "${GREEN}Adding fixed files to the commit...${NC}"
git diff --name-only --cached --relative | grep '\.js\|\.ts$' | xargs -r git add
echo  "${GREEN}Files added successfully.${NC}"

echo  "${GREEN}Pre-commit hook completed successfully.${NC}"
